modLoader = "javafml"
loaderVersion = "[46,)"
issueTrackerURL = "https://github.com/Terrails/colorful-hearts"
license = "MIT"

[[mods]]
modId = "colorfulhearts"
version = "${version}"

displayName = "Colorful Hearts"
authors = "Terrails"
description = ''' A client side mod that replaces multiple vanilla heart rows with a single row using colored hearts '''

logoFile = "assets/colorfulhearts/icon.png"
displayTest = "IGNORE_ALL_VERSION" # ignore everything since its a client only mod

[[dependencies.colorfulhearts]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.colorfulhearts]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "CLIENT"
