modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/Terrails/colorful-hearts"
license = "MIT"

[[mods]]
modId = "colorfulhearts"
version = "${version}"

displayName = "Colorful Hearts"
authors = "Terrails"
description = ''' A client side mod that replaces multiple vanilla heart rows with a single row using colored hearts '''

logoFile = "icon.png"
displayTest = "IGNORE_ALL_VERSION" # ignore everything since it's a client only mod

[[mixins]]
config = "colorfulhearts.mixins.json"
[[mixins]]
config = "colorfulhearts-common.mixins.json"

[[dependencies.colorfulhearts]]
modId = "neoforge"
type = "required"
versionRange = "[20.5,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.colorfulhearts]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.6,)"
ordering = "NONE"
side = "CLIENT"
